branch-defaults:
  main:
    environment: CityBikes-env
    group_suffix: null
environment-defaults:
  CityBikes-env:
    branch: main
    repository: origin
global:
  application_name: CityBikes
  branch: null
  default_ec2_keyname: Aws_Myrole
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
